#!/usr/bin/env python3
"""
validate_pyshacl.py — W3C-canonical SHACL validation of AppSec Core v1.

Runs pyshacl against the bounded v1 ontology data graph and the COMPOSED
shapes graph (apparatus composition per Option C, programme-lead 2026-05-05).

Apparatus composition (architectural commitment):

  formal/appsec_core/03-shacl/shapes/appsec-core-v0-shapes.ttl
      6 schema-derived ontology shapes (Slice / ControlObjective / Practice /
      Mechanism / Artifact / EvidencePattern). Regenerated by build_shacl.py
      from canonical YAML.

  formal/appsec_core/03-shacl/shapes/consumer-conformance-shapes.ttl
      5 invariant-derived Claim shapes (M1' / M3 / M4 via CO chain /
      M4-card cardinality / M4-card referential integrity). Hand-maintained
      from Decision 0003 + Amendment 1 model invariants. NOT regenerated by
      build_shacl.py.

Both files are ontology-owned and maintained by Archon. This module loads
both, merges them into a single shapes graph, and runs pyshacl against the
composition. Apparatus tags (apparatus-shacl-pyshacl-vN) declare the two
file commit anchors explicitly.

Persists conforms boolean + per-node results graph + human-readable report
as Archon-side evidence for P1-C / Pα citation. Complements the in-house
bounded_subset_validator (per-shape granular, limited constraint subset)
with engine-parity attestation using a W3C-canonical SHACL engine.

Inputs (Archon-owned):
  formal/appsec_core/02-owl/exports/appsec-core-v0-bounded-v1.ttl
  formal/appsec_core/03-shacl/shapes/appsec-core-v0-shapes.ttl
  formal/appsec_core/03-shacl/shapes/consumer-conformance-shapes.ttl

Outputs (written under formal/appsec_core/05-validation/reports/):
  appsec-core-v1-pyshacl-summary.json       structured summary (records both shape files + composed graph SHA)
  appsec-core-v1-pyshacl-report.txt          pyshacl's human-readable report
  appsec-core-v1-pyshacl-results-graph.ttl   pyshacl's results graph serialized (R-1 evidence)

Usage:
  python3 -m appsec_core_formalization.validate_pyshacl

Dependencies: pyshacl, rdflib (not listed in sbd-toe-ontology/pyproject.toml;
install via pip or use a venv. Reference environment: pyshacl 0.31.0, rdflib 7.6.0.)
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from rdflib import Graph
    import pyshacl
except ImportError as e:
    print(f"ERROR: missing dependency ({e}). Install with: pip install pyshacl rdflib", file=sys.stderr)
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parents[5]
OWL_FILE = REPO_ROOT / "formal/appsec_core/02-owl/exports/appsec-core-v0-bounded-v1.ttl"
SHAPES_FILE_ONTOLOGY = REPO_ROOT / "formal/appsec_core/03-shacl/shapes/appsec-core-v0-shapes.ttl"
SHAPES_FILE_CONSUMER = REPO_ROOT / "formal/appsec_core/03-shacl/shapes/consumer-conformance-shapes.ttl"
SHAPES_FILES = (SHAPES_FILE_ONTOLOGY, SHAPES_FILE_CONSUMER)
REPORTS_DIR = REPO_ROOT / "formal/appsec_core/05-validation/reports"

SUMMARY_OUT = REPORTS_DIR / "appsec-core-v1-pyshacl-summary.json"
REPORT_OUT = REPORTS_DIR / "appsec-core-v1-pyshacl-report.txt"
RESULTS_GRAPH_OUT = REPORTS_DIR / "appsec-core-v1-pyshacl-results-graph.ttl"


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def current_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


def count_violations(results_graph: Graph) -> int:
    from rdflib import URIRef
    from rdflib.namespace import RDF
    SH_VALIDATION_RESULT = URIRef("http://www.w3.org/ns/shacl#ValidationResult")
    return sum(1 for _ in results_graph.triples((None, RDF.type, SH_VALIDATION_RESULT)))


def main() -> int:
    if not OWL_FILE.exists():
        print(f"ERROR: data graph not found at {OWL_FILE}", file=sys.stderr)
        return 2
    for shapes_path in SHAPES_FILES:
        if not shapes_path.exists():
            print(f"ERROR: shapes graph not found at {shapes_path}", file=sys.stderr)
            return 2

    data_graph = Graph()
    data_graph.parse(str(OWL_FILE), format="turtle")
    # Apparatus composition (Option C, programme-lead 2026-05-05): merge the
    # 6 schema-derived ontology shapes with the 5 hand-maintained Claim shapes
    # into a single shapes graph before validation.
    shapes_graph = Graph()
    for shapes_path in SHAPES_FILES:
        shapes_graph.parse(str(shapes_path), format="turtle")

    # Capture canonical triple counts BEFORE pyshacl.validate(), because
    # pyshacl mutates the shapes_graph in place (injects ~2 bookkeeping
    # triples). The canonical count is what a pure rdflib parse reports and
    # matches the bounded_subset_validator summary.
    data_triple_count_canonical = len(data_graph)
    shape_triple_count_canonical = len(shapes_graph)

    conforms, results_graph, results_text = pyshacl.validate(
        data_graph,
        shacl_graph=shapes_graph,
        inference="none",
        abort_on_first=False,
        meta_shacl=False,
        advanced=False,
        js=False,
        debug=False,
    )

    data_triple_count_post_validate = len(data_graph)
    shape_triple_count_post_validate = len(shapes_graph)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_OUT.write_text(results_text or "", encoding="utf-8")
    results_graph.serialize(destination=str(RESULTS_GRAPH_OUT), format="turtle")

    summary = {
        "status": "conforms" if conforms else "violations",
        "validator": "pyshacl",
        "engine_version": pyshacl.__version__,
        "rdflib_version": __import__("rdflib").__version__,
        "scope": "AppSec Core v1 bounded OWL + SHACL — W3C-canonical engine validation (apparatus composition: ontology shapes + consumer-conformance shapes)",
        "data_graph": str(OWL_FILE.relative_to(REPO_ROOT)),
        "data_graph_sha256": sha256_of(OWL_FILE),
        "shapes_graph_composition": [
            {
                "file": str(SHAPES_FILE_ONTOLOGY.relative_to(REPO_ROOT)),
                "sha256": sha256_of(SHAPES_FILE_ONTOLOGY),
                "role": "schema-derived ontology shapes (regenerated by build_shacl.py)",
            },
            {
                "file": str(SHAPES_FILE_CONSUMER.relative_to(REPO_ROOT)),
                "sha256": sha256_of(SHAPES_FILE_CONSUMER),
                "role": "invariant-derived consumer-conformance shapes (hand-maintained from Decision 0003 + Amendment 1)",
            },
        ],
        "data_triple_count": data_triple_count_canonical,
        "shape_triple_count": shape_triple_count_canonical,
        "data_triple_count_post_validate": data_triple_count_post_validate,
        "shape_triple_count_post_validate": shape_triple_count_post_validate,
        "violation_count": count_violations(results_graph),
        "conforms": bool(conforms),
        "invocation": {
            "inference": "none",
            "abort_on_first": False,
            "meta_shacl": False,
            "advanced": False,
            "js": False,
        },
        "outputs": {
            "report_text": str(REPORT_OUT.relative_to(REPO_ROOT)),
            "results_graph_ttl": str(RESULTS_GRAPH_OUT.relative_to(REPO_ROOT)),
        },
        "commit": current_commit(),
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "notes": [
            "pyshacl is a W3C-canonical SHACL engine. This report complements the in-house bounded_subset_validator (appsec-core-v0-shacl-validation-summary.json) with engine-parity attestation.",
            "Shapes graph is the apparatus composition (Option C, programme-lead 2026-05-05): appsec-core-v0-shapes.ttl (6 schema-derived ontology shapes, regenerated by build_shacl.py) merged with consumer-conformance-shapes.ttl (5 invariant-derived Claim shapes, hand-maintained from Decision 0003 + Amendment 1). Both files ontology-owned, maintained by Archon. Each file's SHA256 recorded individually in shapes_graph_composition.",
            "Shapes use the constraint subset {minCount, maxCount, datatype, class, pattern, in} plus sh:sparql for the consumer-conformance shapes. The bounded validator only covers the first set; pyshacl is the canonical engine for the full composition.",
            "results_graph.ttl persists the W3C SHACL Validation Report graph per R-1 (persist per-shape pyshacl output, not just conforms boolean).",
            "shape_triple_count and data_triple_count are the canonical pre-validate counts (pure rdflib parse of the bytes SHA256-pinned above). pyshacl.validate() mutates the shapes_graph in place, injecting bookkeeping triples; the post-validate counts are exposed separately for transparency. Cite the canonical counts.",
        ],
    }
    SUMMARY_OUT.write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"pyshacl engine:        {pyshacl.__version__}")
    print(f"data graph triples:    {summary['data_triple_count']}")
    print(f"shapes graph triples:  {summary['shape_triple_count']}")
    print(f"conforms:              {conforms}")
    print(f"violation count:       {summary['violation_count']}")
    print(f"summary:               {SUMMARY_OUT.relative_to(REPO_ROOT)}")
    print(f"report:                {REPORT_OUT.relative_to(REPO_ROOT)}")
    print(f"results graph:         {RESULTS_GRAPH_OUT.relative_to(REPO_ROOT)}")
    return 0 if conforms else 1


if __name__ == "__main__":
    sys.exit(main())
